remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

title: TAPL
description: Types and Programming Languages â€” A modern compiler frontend framework for creating strongly typed programming languages.
